package gui;

import java.awt.image.BufferedImage;
import model.*;

/**
 *
 * @author tadaki
 */
public class MainForm extends javax.swing.JFrame {

    private BaseModel model;
    private final BaseModel[] modelInstances = {
        new Sierpinski(), new CantorMaze(), new KochCurve(),
        new Tree(),new Dragon3(),new TwinChristmasTree(),
    new BarnsleyFern(),new Sierpinski2(),};

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        for (BaseModel m : modelInstances) {
            models.addItem(m.getClass().getSimpleName());
        }
        model = modelInstances[0];
        setModel();
        drawPanel.setImgage(model.getImage());
    }

    private final void setModel() {
        model.initImage(drawPanel.getWidth(), drawPanel.getBackground(), drawPanel.getForeground());
        model.setAffine();
        drawPanel.setImgage(model.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        quit = new javax.swing.JButton();
        next = new javax.swing.JButton();
        showMap = new javax.swing.JButton();
        models = new javax.swing.JComboBox<>();
        drawPanel = new gui.DrawPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttons.setBackground(new java.awt.Color(204, 255, 204));

        quit.setBackground(new java.awt.Color(255, 255, 204));
        quit.setText("quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        buttons.add(quit);

        next.setBackground(new java.awt.Color(255, 255, 204));
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        buttons.add(next);

        showMap.setBackground(new java.awt.Color(255, 255, 204));
        showMap.setText("showMap");
        showMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMapActionPerformed(evt);
            }
        });
        buttons.add(showMap);

        models.setBackground(new java.awt.Color(255, 204, 204));
        models.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelsActionPerformed(evt);
            }
        });
        buttons.add(models);

        getContentPane().add(buttons, java.awt.BorderLayout.NORTH);

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        drawPanel.setForeground(new java.awt.Color(255, 0, 0));
        drawPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
    }//GEN-LAST:event_quitActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        BufferedImage img = model.oneUpdate();
        drawPanel.setImgage(img);
    }//GEN-LAST:event_nextActionPerformed

    private void showMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMapActionPerformed
        BufferedImage img = model.showMap();
        drawPanel.setImgage(img);
    }//GEN-LAST:event_showMapActionPerformed

    private void modelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelsActionPerformed
        int k = models.getSelectedIndex();
        model = modelInstances[k];
        setModel();
    }//GEN-LAST:event_modelsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons;
    private gui.DrawPanel drawPanel;
    private javax.swing.JComboBox<String> models;
    private javax.swing.JButton next;
    private javax.swing.JButton quit;
    private javax.swing.JButton showMap;
    // End of variables declaration//GEN-END:variables
}
