package gui;

import java.awt.Font;
import java.awt.image.BufferedImage;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import model.*;

/**
 *
 * @author tadaki
 */
public class NewJFrame extends javax.swing.JFrame {

    private final Font font;

    private AbstractFractal model;
    private final AbstractFractal[] modelInstances = {
        new Sierpinski(), new CantorMaze(), new KochCurve(),
        new Tree(), new Dragon3(), new TwinChristmasTree(),
        new BarnsleyFern(), new Sierpinski2(),};
    private final ButtonGroup fractalGroup;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        font = new java.awt.Font("Yu Gothic UI", 0, 24);
        fractalGroup = new ButtonGroup();
        for (AbstractFractal m : modelInstances) {
            JCheckBoxMenuItem item = new JCheckBoxMenuItem(m.getClass().getSimpleName());
            item.addActionListener((java.awt.event.ActionEvent evt) -> {
                model = m;
                setModel();
            });
            item.setFont(font);
            modelMenu.add(item);
            fractalGroup.add(item);
        }
        model = modelInstances[0];
        JButton next = new JButton("next");
        next.setFont(font);
        next.addActionListener((java.awt.event.ActionEvent evt) -> {
            BufferedImage img = model.oneUpdate();
            drawPanel.setImgage(img);
        });
        menuBar.add(next);
        JButton showMap = new JButton("show Map");
        showMap.setFont(font);
        showMap.addActionListener((java.awt.event.ActionEvent evt) -> {
            BufferedImage img = model.showMap();
            drawPanel.setImgage(img);
        });
        menuBar.add(showMap);
        pack();
    }

    private final void setModel() {
        model.initImage(drawPanel.getWidth() - 20, drawPanel.getBackground(), drawPanel.getForeground());
        model.setAffine();
        drawPanel.setImgage(model.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new gui.DrawPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        modelMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawPanel.setForeground(new java.awt.Color(255, 0, 0));
        drawPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        quit.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        quit.setText("quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        fileMenu.add(quit);

        menuBar.add(fileMenu);

        modelMenu.setText("model");
        modelMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        menuBar.add(modelMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.DrawPanel drawPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu modelMenu;
    private javax.swing.JMenuItem quit;
    // End of variables declaration//GEN-END:variables
}
